### PR TITLE
#49 Feat/query all ever gifted punks

### PR DESCRIPTION
**Pull request by eenagy**
This tab will show all the punks that have ever been gifted. Same rules of sorting by newest at the top, apply.
Timestamp needed to be added after merge #48
Also, created a new way to show crypto punks, which has a little overlapping on mobile. Let me know if the design is something preferable, and I will fix the mobile issue with it.

### CODE REVIEW

**Comment by nazariyv** [comment]
I LOVE the cleaner design. Didn't noticce any mobile overlap :)

But I have a few very minor comments. 

(1) The tab currently gifted isn't showing anything, but there are a number of punks being gifted right now. The definition of the punks that are being gifted right now is when **the end tenancy date is in the future**.

(2) The tab of all ever gifted isn't showing all the historical **and** current punks. (This could be a problem with the subgraph, whereby it deletes the punks that are no longer active)

**Comment by eenagy** [comment]
> I LOVE the cleaner design. Didn't notice any mobile overlap :)

The mobile overlap happens with longer hour values: 11:23 pm, it looks minor, but still.

> But I have a few very minor comments.
> 
> (1) The tab currently gifted isn't showing anything, but there are a number of punks being gifted right now. The definition of the punks that are being gifted right now is when **the end tenancy date is in the future**.

done

> (2) The tab of all ever gifted isn't showing all the historical **and** current punks. (This could be a problem with the subgraph, whereby it deletes the punks that are no longer active)

Maybe because the tenantId for the expired ones set back to "0x0000000000000000000000000000000000000000", but just guessing. I only get 6 punks back from the API alltogether.

**Comment by nazariyv** [comment]
> Maybe because the tenantId for the expired ones set back to "0x0000000000000000000000000000000000000000", but just guessing. I only get 6 punks back from the API altogether.

where have you noticed this?

**Comment by eenagy** [comment]
> > Maybe because the tenantId for the expired ones set back to "0x0000000000000000000000000000000000000000", but just guessing. I only get 6 punks back from the API altogether.
> 
> where have you noticed this?

Queries, I see this filter:

      where: { tenant_not: "0x0000000000000000000000000000000000000000" }

Not sure if the tenant is set back, just see the filter.

**Comment by nazariyv** [comment]
and here is the query, in case subgraph does not load for you:

```
{
    provenances {
    	id
      minSalePriceInWei
      cryptopunk {
        id
      }
      tenancyDates {
        id
        start
      }
    }
}
```

**Pull request merged**
